<?php 

	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$title = $block->getConfig('title');
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$rows = $block->getConfig('row');
	
?>
<div class="bestsellerproduct_container_slider">
	<div class="row">
	<h2 class="ma-title">
		<?php echo $title;?>
		<span class="text1">Browse the collection of our best selling and top interesting products.</span> 
		<span>You'll definitely find what you are looking for.</span> 
	</h2>
	<div id="bestseller_product_slider" class="owl-carousel">
		<?php 
		$saleItems =  $block -> getBestsellerProduct(); 
		$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
		$image = 'new_products_content_widget_grid';
		$type = 'widget-new-grid';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
		$i=0;
		foreach($saleItems as $_item) { 
				$productImage = $block->getImage($_item, $image);
			?>
			
				<?php if($i++%$rows==0) { ?>
					<div class="item">	
				 <?php } ?>
					<div class="item-inner">
						<div class="product-item-info">
							<div class="image-container">
								<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
									<?php echo $productImage->toHtml() ?>
								</a>
								<div class="product-action">
									<div class="actions-primary">
										<?php if ($_item->isSaleable()): ?>
											<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
												<button class="action tocart primary"
														data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
														type="button" title="<?php echo __('Add to Cart') ?>">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											<?php else: ?>
												<?php
													$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
													$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
												?>
												<button class="action tocart primary"
														data-post='<?php echo $postData; ?>'
														type="button" title="<?php echo __('Add to Cart') ?>">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											<?php endif; ?>
										<?php else: ?>
											<?php if ($_item->getIsSalable()): ?>
												<div class="stock available"><span><?php echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								</div>
							
									<div class="add-to-links" data-role="add-to-links">
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<a href="#"
											   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
											   class="action towishlist" data-action="add-to-wishlist"
											   title="<?php echo __('Add to Wishlist') ?>">
												<span><?php echo __('Wishlist') ?></span>
											</a>
										<?php endif; ?>
									</div>
								
								
							</div>
							<div class="box-info">
								<div class="product-name">
										<strong class="product-item-name">
											<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
											   href="<?php echo $block->getProductUrl($_item) ?>"
											   class="product-item-link">
												<?php echo $block->escapeHtml($_item->getName()) ?>
											</a>
										</strong>
										
									<?php //echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>		
									<?php
										echo $block->getProductPrice($_item);
									 ?>
									
								</div>	
							</div> 
						</div>							
					</div>
					<?php if($i%$rows==0 || $i == count($saleItems)) { ?>
				</div>
			  <?php }?>
		<?php 
		}
		?>
</div>
</div>
</div>
<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
	
   $("#bestseller_product_slider").owlCarousel({ 
		autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
		slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
		navigation : <?php if($show_navigation) echo 'true'; else echo 'false'; ?>,
		stopOnHover : true,
		pagination : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
		addClassActive : true,
		scrollPerPage:false,
		items : 4,
		itemsDesktop : [1199,3],
		itemsDesktopSmall : [992,2],
		itemsTablet: [767,2],
		itemsMobile : [479,1]
   });
   
});
</script>   